#project
server:
  port: 8080

#db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa
  jpa:
    show-sql: true
    hibernate:
    properties:
      hibernate:
        format_sql:
        format_use_sql_comments: true
Spring:
  jpa:
    hibernate:
      ddl-auto: create